#! /bin/sh

bspc monitor DP-3 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# for nord
bspc config focused_border_color "#5e81ac"
bspc config active_border_color "#4c566a"
bspc config normal_border_color "#4c566a"

~/.scripts/autostart.sh
